### ISSUE TITLE
Client Version Idea

### ISSUE THREAD

**Issue by Stroell** [jonasatgit/updatereporting#3]
To make the Reports easier readable, you can show 'current' if the client version is up to date - if not just display the version.

For example:

`Declare @AgentMaxVersion  NVARCHAR(256)
  SET @AgentMaxVersion = (Select max(ClientVersion) from CM_UpdatePackages where state = '196612')
  
  Select
    [Agent Version1] = case when @AgentMaxVersion = CDR.ClientVersion then 'Current'
                        else CDR.ClientVersion end,`

![grafik](https://user-images.githubusercontent.com/42348774/99398261-7a090c80-28e4-11eb-962c-78c015e05e32.png)

Cheers,
Stefan

**Comment by jonasatgit** [comment]
At the moment the product has no view exposed to the SSRS SQL role. Adding the client info therefore would require a rights-change in SQL and a direct query against a table which in ConfigMgr is not supported. Great idea, but not feasible at the moment.
